version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_server
    ports:
      - "5672:5672"   # For RabbitMQ messaging
      - "15672:15672" # For RabbitMQ management UI